--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AIPTU/PlayerWarn
build-by-default: true
branches:
- master
projects:
  PlayerWarn:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
