name: PlayerWarn
main: aiptu\playerwarn\PlayerWarn
version: 1.2.0
api: [5.0.0]
author: AIPTU
permissions:
  playerwarn.command.warn:
    description: Permission to use the /warn command
    default: op
  playerwarn.command.warns:
    description: Permission to use the /warns command
    default: true
  playerwarn.command.clearwarns:
    description: Permission to use the /clearwarns command
    default: op
  playerwarn.command.delwarn:
    description: Permission to use the /delwarn command
    default: op
  playerwarn.command.editwarn:
    description: Permission to use the /editwarn command
    default: op
  playerwarn.bypass:
    description: Permission to bypass being warned
    default: op
